### ISSUE TITLE
cucumber-expressions: escape regex special characters

### ISSUE THREAD

**Issue by charlierudolph** [cucumber/cucumber#103]
In the javascript variant, the step text `Lucy is at [0, 0]` generates the cucumber expression `Lucy is at [{arg1:int}, {arg2:int}]`. However, this generated cucumber expression does not match the step.

I believe in order to fix this, I believe we need to escape the special characters (in this case the brackets) in the string when creating the regular expression from the string.

See cucumber/cucumber-js#732

**Comment by jenisys** [comment]
@charlierudolph @aslakhellesoy 
I think the current solution in #106 for the escaping-mechanism in cucumber-expression from Charly has at least one hole: braces need to be escaped, too (AFAIK). Because braces are used to specify cardinality-ranges in regex-patterns.

**Comment by aslakhellesoy** [comment]
Hey @jenisys - I think you're right! Want to send us a patch? Or how about a whole Python implementation :-P

**Comment by charlierudolph** [comment]
Braces and parenthesis already have special meaning in cucumber expressions and get replaced already.

**Comment by jenisys** [comment]
Thanks, Charly for double-checking. I just looked at your escaping-mechanism for the special characters and what was considered for escaping.

@aslakhellesoy 
I would love too to provide the Python implementation. Sadly, I am rather busy right now. I have only some time to peek into all the changes you and the others are doing. The good news is, at least for the braces, the escaping mechanism was already written a few years ago (see: https://github.com/r1chardj0n3s/parse/blob/master/parse.py#L743). I need to check if the other cases are also covered.

**Comment by aslakhellesoy** [comment]
Oh yes, @charlierudolph is right, *curly braces* `{}` and *parenthesis* `()` (which Brits [confusingly](https://separatedbyacommonlanguage.blogspot.co.uk/2006/08/parentheses-and-brackets.html?m=1) call *brackets*) are not escaped because they are being consumed when the expression is parsed and converted to a RegExp.

**Comment by aslakhellesoy** [comment]
On a related note, ticket #107 is open. Should we allow people to escape parenthesis and curly braces, or is  ot being able to do that just a hypothetical problem that doesn't need to be solved? I.e can we wait until someone says they need it?

**Comment by jenisys** [comment]
After thinking about it, *curly braces* occur rather seldom in natural language. *Parenthesis* on the other side may occur (not often but) in some cases. If you (meaning someone in the team) has time to provide a blueprint solution for the latter case, it is OK. Otherwise, waiting for someone to ask for it is also OK (probably better). But is always good to be aware of the limitations that are not covered yet.

NOTE: I made a quick-check over my the aruba-like steps (> 100 step definitions) that I am using. Neither *curly braces* nor *parenthesis* are used. You have probably a similar experience with the step definitions that you are using.
