### ISSUE TITLE
Include comments inside html report

### ISSUE THREAD

**Issue by fslev** [cucumber/cucumber#1364]
Right now, Gherkin comments are not included inside the Html report.
Sometimes, comments are providing additional information that simply cannot be included inside a Gherkin step.
This feature would be very useful

**Comment by luke-hill** [comment]
So the html report (By default), uses a formatter which doesn't output these. I would think this is by design. The primary reason being comments can be added in a variety of location but "usually" describe one of several things.

The feature proper -> You can add a description underneath the feature
The scenario -> You can amend the title as this is just another descriptor
A step
A tag

For step/tag I agree having a comment would help. But to me if you're commenting steps or tags, it's likely they're not fully functional, or maybe there's some tech debt or something? Do you want business people reading that on reports?

Obviously I've not covered all use cases. Also the way in which the formatter works now new different style html reporters can be made, so maybe some people will disagree with me and go in a different route. That's the beauty of Open Source.

**Comment by davidjgoss** [comment]
Agree with @luke-hill, you can add descriptions to features and scenarios with as much detail as you want. The [docs](https://cucumber.io/docs/gherkin/reference/#descriptions) don't make it super clear but these can be markdown and the html formatter will render it as such.

**Comment by fslev** [comment]
Comments become very useful when you have highly re-usable steps which work with large text data. Thus, you need to explain the business particularities of that step:

For example:
# Create TXT and MX records types
When Create DNS records with requestBody=<pathToFileWithLargeRequestBody> and check response={"status":201}

According to this issue I've raised here:
https://github.com/cucumber/cucumber-jvm/issues/2237
, these comments could be read from the GherkinDocument messages.

However, if current formatter doesn't have comment support, I think we could close this issue.
