### ISSUE TITLE
Improve title of World configuration page

### ISSUE THREAD

**Issue by ncjones** [cucumber/cucumber#2]
The wiki page titled "A Whole New World" is poorly named; the page describes how to configure the execution context of Cucumber scenarios but the title suggests it is introducing the "what and why" of Cucumber. It took me two hours of searching to find that page. I suggest renaming it to something like "Configuring the scenario execution context (World)"

**Comment by olleolleolle** [comment]
In order to meet this request, while still keeping links into the wiki alive, I have:

- created a new page `Configuring the Scenario Execution Context (World)`
- added the full content fro `A Whole New World` to it
- changed the link in the `Table of Contents`
- replaced the content of the `A Whole New World` article with a link to the newly-minted article

**Comment by olleolleolle** [comment]
@ncjones Does this meet your need? https://github.com/cucumber/cucumber/wiki/Configuring-the-Scenario-Execution-Context-(World)

**Comment by ncjones** [comment]
Yes :) Thanks!

**Comment by olleolleolle** [comment]
Then, I'll close this issue as fixed. Thanks, ciao.

As a side-note: the documentation effort's history _is_ moving forward. Here's a timeline of the efforts: https://github.com/cucumber/docs.cucumber.io#old-documentation
