### ISSUE TITLE
API for stateless step definitions

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#214]
Currently, the only way to pass state between step definitions is by storing state as instance variables.

This is cumbersome in some languages, in particular for Java where it becomes tricky to share state between classes. DI is the only way to address this.

For other languages (such as Ruby and JavaScript) the `World` often becomes a huge object holding all kinds of different state used by various step definitions.

I would like to propose an alternative API for Step Definitions where:

* Each step definition (or hook) can return a value
* This value is passed to the next step definition
* Statically typed languages can use custom types

This would remove the need for a World or DI. It would reduce coupling and make it more explicit what is passed between step definitions.

We'll use this issue to discuss the implications of this in various implementations, and to come up with an API for various languages such as Java, Ruby and JavaScript (at least).

Once we're happy with the API we can create new issues to implement this in various Cucumbers.

(I've been thinking about this for a while, and I'm glad I am not the only one! See cucumber/cucumber-jvm#1136)

**Comment by mpkorstanje** [comment]
I think this solution trades a coupling a between step definitions and the World/DI modules for a coupling to the order in which steps in gherkin must be written. So I don't think this can be used to completely replace the World or DI modules. In the worst case you end up passing the World between steps.

For example take a website like Gmail that personalizes your account even when you  are not logged in because it recognizes that nobody else ever uses that machine.

```feature
Given I am a specific kind of customer
And I have a login account that was previously used to login
When use the website
Then I am greeted with my name
```

In this scenario I'd have to pass the information about the customer (his name) from the first step all the way to last step through one or more steps that don't use the information.

But other then that yeah this can useful.

**Comment by mpkorstanje** [comment]
I found some past discussion about the same issue in Scala.

https://github.com/cucumber/cucumber-jvm/issues/451

**Comment by paoloambrosio** [comment]
I am very much in favour of pure functions, or better of allowing both pure and impure step definitions for languages that were FP is not the main paradigm.

I think DI framework support is still needed to inject what is not part of the scenario context into the step definition class: components from the application or shared test dependencies (e.g. Selenium). In this way we don't need to handle different scopes for context parameters, as they should always have scenario scope, but we'd be flexible.
