### ISSUE TITLE
[query] [docs] Citable reference for Gherkin spec?

### ISSUE THREAD

**Issue by kwill** [cucumber/cucumber#246]
I would like to reference the complete Gherkin specification. Ideally this would be an implementation-independent spec, but that is not necessary. (My understanding is that Gherkin is Cucumber's implementation of [Dan North's story format](https://dannorth.net/whats-in-a-story/), and that it has since been adopted by Behave, Behat and others.)

So far the best definitions I have found are:
* https://cucumber.io/docs/reference#gherkin
* https://github.com/cucumber/cucumber/wiki/Gherkin (more detail)
* https://pythonhosted.org/behave/gherkin.html#gherkin-feature-testing-language (more detail, non-Cucumber)

Is any of these the official or de facto specification? Or is there a page I've missed?

**Comment by aslakhellesoy** [comment]
The definitive Gherkin specification is its [grammar](https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin.berp), its [tests](https://github.com/cucumber/cucumber/tree/master/gherkin/testdata) and the [AST](https://github.com/cucumber/cucumber/blob/master/gherkin/README.md#ast) documentation.

> My understanding is that Gherkin is Cucumber's implementation of Dan North's story format

That article was written a couple of years after the Gherkin language was designed. You can read more about the history of Gherkin and Cucumber [here](https://www.quora.com/Why-is-the-Cucumber-tool-for-BDD-named-as-such).

The Gherkin language has evolved gradually since 2003, and first got its name and grammar in 2008, in the early Cucumber days.

**Comment by kwill** [comment]
Thanks for the links and historical context!
