### ISSUE TITLE
Expressions being parsed incorrectly on 6.11.x

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#281]
_From @AlexBHarley on October 6, 2017 8:31_

Given the following step

```
When client A queues an event "emit_event" with data { "x": "my_data" }
```

And matching step definition

```
When(/^(.+) queues? (?:an|the|"(\d+)") events? "([^"]*)"(?: with data ("[^"]*"|\d+|\{.*\}))?$/, (clientExpression, numEvents, eventName, rawData) => {
  console.log(clientExpression, numEvents, eventName, rawData)
  // client A, NaN, emit_event, { "x": "my_data" }
})
```

We expect the following to be printed

```
// client A, undefined, emit_event, { "x": "my_data" }
```

I have seen other issues regarding this but they seem to now be resolved. I also looked at your commit history and can see that you're only testing on node 8 now? Our tests run correctly on node 8 but fail on 6.

I have managed to get this to pass by manually setting the cucumber-expressions version to 4.0.1. 

node: 6.11.x
cucumber: 3.0.4
cucumber-expressions: 4.0.4 & 4.0.3
os: Mac OS X 10.12.6 and whatever the default Linux machine Travis-CI use

_Copied from original issue: cucumber/cucumber-js#945_

**Comment by aslakhellesoy** [comment]
@AlexBHarley I cannot reproduce this. I'm getting `client A, NaN, emit_event, { "x": "my_data" }` with both Node 8.6.0 and 6.11.4.

I don't understand why you would expect `undefined` instead of `NaN` either. The 2nd capture group - `(\d+)` will be transform to a `Number` by the built-in `{int}` parameter type, using `parseInt`.

The raw value of the 2nd group is `undefined`, and `parseInt(undefined)` is `NaN` for both Node 6 and 8.

If you can make a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) in a git repo that reproduces this I will have another look.

**Comment by AlexBHarley** [comment]
Sorry the initial code snippet I provided was a bit confusing, the issue is that we're getting `NaN` instead of `undefined`, so you are able to reproduce.

This is a problem for us as you can see in [this step implementation](https://github.com/deepstreamIO/deepstream.io/blob/master/test-e2e/steps/http/http-steps.js#L82) (explicitly the `numEvents` variable). We have checks that if no value is provided, it should be `undefined` instead of `NaN`.

Not familiar with your code base but I've nailed down the change to somewhere between `cucumber-expressions@4.0.2` and `cucumber-expressions@4.0.3`. We now have a fork [here](https://github.com/deepstreamIO/cucumber-js) where the only change I've made is

```
"cucumber-expressions": "^4.0.3"
```

to

```
"cucumber-expressions": "4.0.2"
```

in the `package.json` file.

**Comment by aslakhellesoy** [comment]
I'm even more confused.

* Initially you say the behaviour is inconsistent between Node 6 and 8.
* Now I have the impression it's inconsistent between cucumber-expressions 4.0.3 and 4.0.4 (in addition to, or instead of the node version?)
* `When we queue something events` doesn't even match the regexp at all, so the stepdef won't run

Please provide a git repo I can clone and clarify my points of confusion.

**Comment by aslakhellesoy** [comment]
Any update on this @AlexBHarley?

**Comment by AlexBHarley** [comment]
Sorry stretched on time so haven't been able to create the repo, but it may be easier for us to just accept `NaN` as the expected value.

**Comment by aslakhellesoy** [comment]
Ok, I'm closing this
