### ISSUE TITLE
how to prepare json file from feature files?

### ISSUE THREAD

**Issue by dipakbachhav** [cucumber/cucumber#332]
Is there any way to prepare json file from .feature file in BDD?

I am trying to create json file where input source of data is .feature file
 

    Feature: Testing a REST API 
           Scenario: Create student account using post method
           Given api is up and running for post method
           When i create json with below valuesand hit rest api

     | Student_id            |Name       |   CityName    | State  |PostCode	   |Tel			   |
     |		0101			 |Andrew	 |  Leeds        |		  | SO143FT	   | 345345345345  |
     |		0102			 |Smith	     |  NewCastle    |		  | SO143LN    | 345345345345  |
           Then Status is 201

   

Below is he sample json file.

          {
                "Student_id": 0101,
                "Name": "test",
                "CityName": "test",
                "State": "TT",
                "PostCode": 89098,
                "Tel": "(000)- 000-0000",
                
            }

**Comment by mlvandijk** [comment]
Hello Dipak, 
Welcome!
For questions please one of the [support options](https://cucumber.io/support).
GitHub issues are used to report bugs or request features.
I'm going to close this issue here. (Also, I've already provided some information on how you could do this on [StackOverflow](https://stackoverflow.com/questions/48487298/how-to-prepare-json-file-from-feature-file/48495736?noredirect=1#comment84371640_48495736)
