### ISSUE TITLE
cucumber-expressions-ruby: Multiline regexp not allowed in ParameterType class

### ISSUE THREAD

**Issue by aidamanna** [cucumber/cucumber#465]
## Summary
When creating a parameter type, it doesn't allow to define multiline regexp.

## Expected Behavior
You can define a multiline regexp with `/m` when creating a parameter type.

## Current Behavior
If using `/m` regex modifier to create a multiline regexp when defining a new parameter type, cucumber complaints with `ParameterType Regexps can't use option Regexp::MULTILINE`

## Steps to Reproduce (for bugs)
1. Create the following  parameter type:
```
ParameterType(
  name:        'color',
  regexp:      /(red|blue|pink|green
|orange|yellow|)/m,
  transformer: ->(color) { color }
)
```
2. Run test that uses this parameter type

## Context & Motivation
When having a very long line, being able to break it makes code more readable (+ Rubocop doesn't complaint)

## Failing test
/cucumber/cucumber-expressions/ruby/spec/cucumber/cucumber_expressions/parameter_type_spec.rb
```
it 'allows multiline flag on regexp' do
   expect do
      ParameterType.new('multiline', /[a-z]+/m, String, lambda {|s| s}, true, false)
    end.not_to raise_error(CucumberExpressionError
end
```

**Comment by danascheider** [comment]
@aslakhellesoy This is traceable to [these lines](https://github.com/cucumber/cucumber/blob/5a098df3fc609131b75188db509913375aae9348/cucumber-expressions/ruby/lib/cucumber/cucumber_expressions/parameter_type.rb#L66-L76) in cucumber-expressions. Is the reason these are disallowed because newlines in param types mess with Gherkin parsing? If not, why aren't they allowed? At first blush, it looks like simply removing `'MULTILINE'` from that array solves the problem, but I'm assuming there's a good reason this fix wouldn't be feasible on the whole.
