### ISSUE TITLE
Expose ParameterType internal 'transformer' field via getter

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber#489]
_From @lgoldstein on October 2, 2018 5:12_

## Summary

The `ParameterType` exposes all its internal fields via public getters - except for the _transformer_. I see no reason why it should not be exposed as well via such a getter - especially since it can be re-used by other code. E.g., in our project, I would like to automatically use it for internal conversions related to the type the parameter represents.

## Expected Behavior

```java
public CaptureGroupTransformer<T> getTransfomer() {
    return transformer;
}
```
## Current Behavior

```java
private final CaptureGroupTransformer<T> transformer;
```

## Possible Solution

```java
public CaptureGroupTransformer<T> getTransfomer() {
    return transformer;
}
```
## Context & Motivation

The `ParameterType` class contains useful code beyond the immediate _Cucumber_ usage - in our case, the transformer that can be used to convert a string (or a list of them) into some internal type. We would like to use the transformer for "internal" (i.e., non-Cucumber related) conversions as well in order to avoid code duplication as well have a standard and consistent way to execute such conversions.

## Your Environment

* Version used: 4.0.0
* Operating System and version: Fedora 28 + OpenJDK 1.8.181
* Link to your project: N/A

_Copied from original issue: cucumber/cucumber-jvm#1473_

**Comment by aslakhellesoy** [comment]
Hi @lgoldstein,

I’d be happy to add this if you send a pull request!

Aslak

**Comment by mpkorstanje** [comment]
While the transform it self is reusable I don't see a good reason to expose it. While convenient for the given use case the use case it self is not a good practice. 

1. It creates a dependency from the non-cucumber related framework onto cucumber. This dependency should be the other way around. The downstream conversion mechanism should be plugged into cucumber.

2. Every bit of the API we open up without designing it as an extension point is a bit of the API we can't easily change. Cucumber is a big project so limiting the exposed surface area let's us evolve it quickly without breaking anything down stream.

**Comment by lgoldstein** [comment]
>> It creates a dependency from the non-cucumber related framework onto cucumber. This dependency should be the other way around. The downstream conversion mechanism should be plugged into cucumber.

True, but why is it a decision that the _Cucumber_ team is making for **my** project ? Isn't this something that we as the specific project developers should make ? Can't we be trusted to understand the ramifications of such a decision and yet decide to accept them ? Here is the use-case for our project - the non-Cucumber code is used only for **tests framework** - none of it makes it into production. Since we chose to base our testing framework on _Cucumber_ why can't I use any of its features ? How would the **already existing** dependency on _Cucumber_ be made "worse" if I decide to use its transformers ?

BTW, even if the _Cucumber_ code did make it into production - why is _Cucumber_'s concern how I decide to use its code ? Why do you assume that there can be no reasonable use-case where dependency on _Cucumber_ is allowed ?

**Comment by lgoldstein** [comment]
>> Every bit of the API we open up without designing it as an extension point is a bit of the API we can't easily change. Cucumber is a big project so limiting the exposed surface area let's us evolve it quickly without breaking anything down stream.

True in principle, however (no offense) but based on previous upgrades we did with _Cucumber_ versions (1 -> 2, 2 -> 4) it is anything but

>> evolve it quickly without breaking anything down stream

therefore, I fail to see how exposing an existing **public** API that adds **no extra functionality** increases the exposed surface area.

**Comment by lgoldstein** [comment]
>> I’d be happy to add this if you send a pull request!

I'll do it, but is a PR really necessary for such a simple change (3 lines...) ?

**Comment by aslakhellesoy** [comment]
Without a PR it will be at the bottom of my TODO list. With a PR it will be higher, as there is less work for others to do :-)

**Comment by lgoldstein** [comment]
Roger Wilco :-))

**Comment by lgoldstein** [comment]
Opened [PR-490](https://github.com/cucumber/cucumber/pull/490)

**Comment by mpkorstanje** [comment]
> I fail to see how exposing an existing public API that adds no extra functionality increases the exposed surface area.

You're not just adding a simple getter.

An implementation detail of `ParameterType` is that it wraps `Transformer`  in a `TransformerAdaptor`. Currently this adapter quietly drops all but the first capture group of a regex. Only when using `ParameterType.transform` this is handled properly. Any user of the value returned by the getter has to be aware of this. So now we are effectively leaking implementation details. This is bad. 

Leaking implementation details and leaky abstractions (e.g. XStream, Gherkin) has also been one of the reasons why upgrading major versions of Cucumber has been painful but this is not a good argument to continue in the same fashion.

> Since we chose to base our testing framework on Cucumber why can't I use any of its features ? 

Cucumber does not become extensible simply because you've chosen to use it. It was never designed for extension beyond `Plugin`, `Backend` and `ObjectFactory` interfaces. In fact I am still puzzled how you are even using `ParameterType` in a meaningful way outside of the `TypeRegistryConfigurer`.

**Comment by aslakhellesoy** [comment]
@lgoldstein still waiting for some concrete code examples of how you'd reuse a transformer...

**Comment by aslakhellesoy** [comment]
Closed due to lack of follow-up
