### ISSUE TITLE
gherkin history spec

### ISSUE THREAD

**Issue by AlbanMinassian** [cucumber/cucumber#628]
## Summary

Where find the history of Gherkin language versions ?

gherkin@6 : add rule (2018-09-25 - [changelog](https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md#6013---2018-09-25))
gherkin@5 : ??? - year - before gherkin@6, what new keyword ?
gherkin@4 : ??? - year - before gherkin@5, what new keyword ?
gherkin@3 : ??? - year - before gherkin@4, what new keyword ?
gherkin@2 : ??? - year - before gherkin@3, what new keyword ?
gherkin@1 : ??? - year - what init keyword ?

Thanks

**Comment by aslakhellesoy** [comment]
The Gherkin changelog is where you suggested - [CHANGELOG](https://github.com/cucumber/cucumber/blob/master/gherkin/CHANGELOG.md)

I don't understand the other questions - can you please clarify?

**Comment by AlbanMinassian** [comment]
Is there a history of the Gherkin language in time? The version of the Gherkin v6 language looks more like the version of Cucumber v6.
Ami44

**Comment by jenisys** [comment]
@AlbanMinassian 
You should distinguish between the specification version and the implementation of this specification. Your problem seems to relate to the implementation of the specification. If you think there is something in the gherkin-go implementation, you should issue a problem report and/or provide a pull-request (which is even better).

NOTES:
* Gherkin v6 and support for the different implementation and languages is still evolving (AFAIK)
* Behave uses its own parser implementation of the Gherkin grammar (based on the [gherkin.berp](https://github.com/cucumber/cucumber/blob/master/gherkin/gherkin.berp) grammar description that is mentioned above as reference)
* Based on the `gherkin.berp` grammar description a Rule can have tags (before the Rule keyword). This allows you to select all Scenarios / Examples of this Rule during a test-run by using a Rule tag.

**Comment by jenisys** [comment]
After looking at the `gherkin.berp` grammar again: 
* The Rule currently has no tags (I must have overlooked this "grammar problem")
* BUT: The Rule should have tags for the reason I described above
