### ISSUE TITLE
Improve German translation

### ISSUE THREAD

**Issue by Haukinger** [cucumber/cucumber#707]
There's a pull request (352) that improves the German translation by replacing the atrocious "Szenariogrundriss", but it seems to have been closed and ignored.

Any chances for merging that one or perhaps a new pull request?

**Comment by aslakhellesoy** [comment]
Hi @Haukinger - looks like #352 was accidentally made against `gherkin/c/gherkin-languages.json` rather than the master at `gherkin/gherkin-languages.json`. It was merged, but later overwritten by the master (our build system does this).

Could you please send a new PR against the correct file? Thanks!

**Comment by Haukinger** [comment]
No problem at all, I hope this will make it into Specflow at some point in time. I'll create an issue over there as soon as it's merged here.

**Comment by aslakhellesoy** [comment]
Vielen Dank @Haukinger!

**Comment by aslakhellesoy** [comment]
Closed by #708
