### ISSUE TITLE
cucumber2: scenario name with garbage

### ISSUE THREAD

**Issue by akostadinov** [cucumber/cucumber#768]
In cucuber 1.x I see scenario.name == "scenario name"
In 2.x I see  scenario.name == "Scenario: scenario name"
In 2.x also scenario.title == "Scenario: scenario name"

IMHO one of these should be simple "scenario name"

Update: ditto Scenario outline - both name and title contain: "Scenario Outline: scenario name, Examples (row 1)"

Update 2: It is important for me to know which row of the outline is this and if it is an outline or just a scenario but would be nice to have raw name somewhere. Also a separate method to get row number would be nice. if this is not possible I can live with current implementation. I basically want to know all details. Just parsing strings is not very nice IMHO.

**Comment by mattwynne** [comment]
The root of this is here: https://github.com/cucumber/cucumber-ruby-core/blob/master/lib/cucumber/core/test/case.rb#L93

**Comment by brasmusson** [comment]
I realized that the keyword is still included in the `scenario.name` available to hooks (see [before_hooks.feature](https://github.com/cucumber/cucumber/blob/f5f8ae0635cbca28afc7b9841bec3019229c2a15/features/docs/writing_support_code/before_hook.feature)), In #814 there is a fix for this.

The checks in the Scenario Outline case is not very precise. The actual value of `scenario.scenario_outline.name` is `Scenario Outline: <scenario outline name>, <examples table name> (row <nr>)`, but since the check of newline is missing, the both scenarios in the feature file is passing.
