### ISSUE TITLE
Background Outline support

### ISSUE THREAD

**Issue by ivanoblomov** [cucumber/cucumber#797]
How about extending the Scenario Outline concept to Backgrounds as well?

This would DRY up testing the same scenarios against different user roles, for example:

  Background Outline:
    Given I am logged in as <role>

    Examples:
      | role               |
      | jedi               |
      | rebel             |
      | stormtrooper |

**Comment by mattwynne** [comment]
This has come up on the mailing list before, and I'm personally against it - I think that it will make for less readable feature documents. For me, [readability trumps DRY](http://dannorth.net/2008/06/30/let-your-examples-flow/) in feature files. So I won't be implementing this feature myself.

Sorry to be so negative!

In general, I'd appreciate it if you would discuss ideas like this on [the mailing list](http://groups.google.com/group/cukes), so that we keep this issue tracker free for actual bugs or features being worked on. Thanks for your cooperation!
