### ISSUE TITLE
cannot load such file — 2.2/gherkin_lexer_en

### ISSUE THREAD

**Issue by MauryZ** [cucumber/cucumber#830]
I need a little help. How do I resolve this problem?

When I call cucumber I get the following error:

  *** WARNING: You must use ANSICON 1.31 or higher (https://github.com/adoxa/ansic
on/) to get coloured output on Windows
WARNING: cannot load such file -- 2.2/gherkin_lexer_en
Couldn't load 2.2/gherkin_lexer_en
The $LOAD_PATH was:
lib
C:/Ruby22/lib/ruby/gems/2.2.0/gems/cucumber-1.3.19/bin/../lib
C:/Ruby22/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib
C:/Ruby22/lib/ruby/gems/2.2.0/gems/diff-lcs-1.2.5/lib
C:/Ruby22/lib/ruby/gems/2.2.0/gems/multi_json-1.11.0/lib
C:/Ruby22/lib/ruby/gems/2.2.0/gems/gherkin-2.12.2-x86-mingw32/lib
[...]
System:
Windows 8.1 x64
Ruby 2.2.1 installer

Gems:
gherkin-2.12.2-x86-mingw32
calabash-android-0.5.8
cucumber-1.3.19

**Comment by aslakhellesoy** [comment]
I'm afraid Cucumber on Windows/Ruby requires ruby 2.0.0 (x86). The reason is that the gherkin gem doesn't yet ship with compiled binaries for more recent versions or Ruby, and not for x64.

We're working on a [Gherkin3](https://github.com/cucumber/gherkin3) which will address this issue. See [this post](https://groups.google.com/forum/#!msg/cukes/YLKsqbBMBoI/DYhfFx8GBegJ) for background. I cannot give you an ETA, but it's at least a few months away.

I'm closing this issue since we're not planning to make any more releases of Gherkin2.

**Comment by snowe2010** [comment]
So there's no way to get cucumber working for versions past 2.0 on windows?

**Comment by aslakhellesoy** [comment]
@snowe2010 unfortunately not. We know this is a problem for many, which is why we're working on Gherkin3 and upgrading Cucumber to use it.

**Comment by snowe2010** [comment]
What can I do to help speed up development of Gherkin3?

**Comment by aslakhellesoy** [comment]
Gherkin3 itself is actually pretty mature - we just need to finalise the compiler, which should be fairly simple. There is a [rough version in Java](https://github.com/cucumber/gherkin3/blob/java-compiler/java/src/main/java/gherkin/compiler/Compiler.java) on the `java-compiler` branch, and we need to implement it in the other languages (including Ruby).

You could help by forking the repo and branching off a `ruby-copiler` branch from the `java-compiler` branch and implement it in Ruby (and update the Ruby Makefile to run acceptance tests for the compiled pickles).

When that's done, the next thing we need help with is refactoring `cucumber-core` to use Gherkin3 instead of Gherkin2, which is a much bigger job.

Please continue the discussion on the [cukes](https://cukes.info/support) google group.

**Comment by tooky** [comment]
@aslakhellesoy @mattwynne what do you think about refactoring the existing compiler in `cucumber-ruby-core` to use `gherkin3`'s parser? We can extract that to `gherkin3` once we have it working? It might reduce the integration burden?

**Comment by mattwynne** [comment]
That would be my preference @tooky - one step at a time.

**Comment by aslakhellesoy** [comment]
Sounds like a good idea. Let's keep that discussion in a `ruby-core` ticket if there is more to discuss.
