### ISSUE TITLE
Unable to resolve dependencies. 'Cucumber.Messages 8.0.0' is not compatible with 'SpecFlow 3.1.74 constraint: Cucumber.Messages (>= 6.0.1 && < 7.0.0)'.				

### ISSUE THREAD

**Issue by v-atian** [cucumber/cucumber#842]
Install SpecFlow for VisualStudio 2019 and add specflow nuget package in my solution.

Get the following error when updating Cucumber.Messages 6.0.1 to 8.0.0 in VS2019

Severity	Code	Description	Project	File	Line	Suppression State
**Error		Unable to resolve dependencies. 'Cucumber.Messages 8.0.0' is not compatible with 'SpecFlow 3.1.74 constraint: Cucumber.Messages (>= 6.0.1 && < 7.0.0)'.**

My project is a .net framework class library.				

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Operating System and version:
* Link to your project:

**Comment by aslakhellesoy** [comment]
@SabotageAndi @gasparnagy I believe this issue belongs in the SpecFlow repo. Can you move this issue please?

**Comment by SabotageAndi** [comment]
@aslakhellesoy Sadly you can't move issues into a repository in another organisation.

@v-atian SpecFlow supports currently only Cucumber-Message from 6.0.1 to 7.00. 
This is stated in the dependecies of the NuGet package. 
![image](https://user-images.githubusercontent.com/859801/71965530-262b9280-3200-11ea-84af-6ce1379b52dd.png)
The error you get is from NuGet because of the dependencies we have in the package.

**Comment by luke-hill** [comment]
@SabotageAndi I'll pm you.
