### ISSUE TITLE
Allow tagging steps

### ISSUE THREAD

**Issue by Selvam-N** [cucumber/cucumber#873]
Am using a Multiplatform (Android and IOS), in which most of the steps in the scenario seems to be same except one or two steps. So I don't want to create a duplicate of the steps. So it will be clean and neat if tags are allowed at the steps. Does cucumber allows tags above the steps. Any help is really appreciated.

**Comment by jenisys** [comment]
Gherkin does not support that AFAIK and it would also be pretty confusing for people IMHO.
The normal solution is one of the following:

* Use two scenarios, one tagged with @android and the other one tagged with @ios
* Hide the variation in the step implementation (or below in the test infrastructure). This means that you need to use more general steps (declarative style; indicating the intention) what to do instead of each gory detail (imperative style)

**Comment by aslakhellesoy** [comment]
Agree with @jenisys - if you need conditional execution, handle this in your stepdefs, or create different tagged scenarios. Changing the grammar to support this would not only make Gherkin more complicated and confusing, it would also have huge ripple effects.

**Comment by luke-hill** [comment]
As an example as well you could do (Not sure how you feel, but I've done similar things before

```
When("I do the thing") do
  if @scenario_tags.ios?
    # do iOS thing
  else
    # do android thing
  end
end
```

Or in your gherkin

`Given I am on a <type> system`

and as a step

```
Given("I am on a {word} system") do |system|
  @system_type = system
end
```

Those are a couple of options which are reasonably elegant.

**Comment by harvinders** [comment]
There is one thing in my opinion that would be elegantly solved using step tagging, per step timeouts. Most often we use gherkin to test UI and the same gherkin step is used in multiple scenarios, say tapping a button. However, sometime the timeout requirements are different and tagging timeout would solve this elegantly. 

The alternative would be to either create two versions of the same step definition, one with timeout and one without, which is time consuming and error prone.
